export const mockUniversities = [
  { id: '1', name: 'BBD University', location: 'Lucknow, UP' },
  { id: '2', name: 'BBD ITM', location: 'Lucknow, UP' },
  { id: '3', name: 'BBD NITM', location: 'Lucknow, UP' },
  { id: '4', name: 'AKTU', location: 'Lucknow, UP' },
  { id: '5', name: 'Lucknow University', location: 'Lucknow, UP' },
]

export const mockCourses = [
  'B.Tech Computer Science',
  'B.Tech Information Technology',
  'B.Tech Electronics & Communication',
  'B.Tech Mechanical Engineering',
  'B.Tech Civil Engineering',
  'BCA',
  'BBA',
  'MBA'
]

export const mockPapers = [
  {
    id: '1',
    title: 'Data Structures and Algorithms',
    course: 'B.Tech Computer Science',
    semester: '3rd',
    subject: 'Data Structures',
    subjectCode: 'KCS301',
    examType: 'End Semester',
    academicYear: '2023-2024',
    university: 'BBD University',
    downloads: 1250,
    rating: 4.8,
    uploadedBy: 'Aman Singh',
    createdAt: '2023-12-15T10:00:00Z',
    tags: ['Trees', 'Graphs', 'Dynamic Programming']
  },
  {
    id: '2',
    title: 'Operating Systems Mid Term',
    course: 'B.Tech Computer Science',
    semester: '4th',
    subject: 'Operating Systems',
    subjectCode: 'KCS401',
    examType: 'Mid Semester',
    academicYear: '2023-2024',
    university: 'BBD ITM',
    downloads: 850,
    rating: 4.5,
    uploadedBy: 'Priya Sharma',
    createdAt: '2024-03-10T14:30:00Z',
    tags: ['Process Management', 'Memory', 'Concurrency']
  },
  {
    id: '3',
    title: 'Engineering Mathematics I',
    course: 'B.Tech Information Technology',
    semester: '1st',
    subject: 'Engineering Maths I',
    subjectCode: 'KAS103',
    examType: 'End Semester',
    academicYear: '2022-2023',
    university: 'BBD NITM',
    downloads: 2100,
    rating: 4.9,
    uploadedBy: 'Admin',
    createdAt: '2022-12-20T09:00:00Z',
    tags: ['Calculus', 'Linear Algebra']
  },
  {
    id: '4',
    title: 'Database Management Systems Lab Viva',
    course: 'B.Tech Computer Science',
    semester: '5th',
    subject: 'DBMS',
    subjectCode: 'KCS501',
    examType: 'Lab Viva',
    academicYear: '2023-2024',
    university: 'AKTU',
    downloads: 500,
    rating: 4.2,
    uploadedBy: 'Rahul Verma',
    createdAt: '2024-05-01T11:15:00Z',
    tags: ['SQL', 'Normalization', 'Transactions']
  },
  {
    id: '5',
    title: 'Computer Networks',
    course: 'B.Tech Electronics & Communication',
    semester: '6th',
    subject: 'Computer Networks',
    subjectCode: 'KEC601',
    examType: 'Mid Semester',
    academicYear: '2023-2024',
    university: 'BBD University',
    downloads: 600,
    rating: 4.6,
    uploadedBy: 'Prof. AK Mishra',
    createdAt: '2024-02-18T16:45:00Z',
    tags: ['OSI Model', 'TCP/IP', 'Routing']
  },
  {
    id: '6',
    title: 'Compiler Design',
    course: 'B.Tech Computer Science',
    semester: '6th',
    subject: 'Compiler Design',
    subjectCode: 'KCS602',
    examType: 'End Semester',
    academicYear: '2022-2023',
    university: 'BBD ITM',
    downloads: 430,
    rating: 4.1,
    uploadedBy: 'Neha Gupta',
    createdAt: '2023-06-12T10:20:00Z',
    tags: ['Parsing', 'Lexical Analysis']
  },
  {
    id: '7',
    title: 'Software Engineering',
    course: 'B.Tech Information Technology',
    semester: '5th',
    subject: 'Software Engineering',
    subjectCode: 'KIT501',
    examType: 'End Semester',
    academicYear: '2023-2024',
    university: 'BBD NITM',
    downloads: 720,
    rating: 4.7,
    uploadedBy: 'Vikas Kumar',
    createdAt: '2023-11-05T08:15:00Z',
    tags: ['SDLC', 'Agile', 'Testing']
  },
  {
    id: '8',
    title: 'Business Communication',
    course: 'BBA',
    semester: '1st',
    subject: 'Business Communication',
    subjectCode: 'BBA101',
    examType: 'End Semester',
    academicYear: '2023-2024',
    university: 'Lucknow University',
    downloads: 1100,
    rating: 4.4,
    uploadedBy: 'Sneha Singh',
    createdAt: '2023-12-01T14:00:00Z',
    tags: ['Communication', 'Writing Skills']
  },
  {
    id: '9',
    title: 'Digital Logic Design',
    course: 'B.Tech Electronics & Communication',
    semester: '3rd',
    subject: 'DLD',
    subjectCode: 'KEC301',
    examType: 'End Semester',
    academicYear: '2022-2023',
    university: 'AKTU',
    downloads: 950,
    rating: 4.3,
    uploadedBy: 'Saurabh Pandey',
    createdAt: '2022-12-10T12:30:00Z',
    tags: ['Gates', 'Flip Flops', 'Multiplexers']
  },
  {
    id: '10',
    title: 'Financial Accounting',
    course: 'MBA',
    semester: '1st',
    subject: 'Financial Accounting',
    subjectCode: 'MBA102',
    examType: 'End Semester',
    academicYear: '2023-2024',
    university: 'BBD University',
    downloads: 890,
    rating: 4.8,
    uploadedBy: 'Amit Dubey',
    createdAt: '2023-12-18T09:45:00Z',
    tags: ['Accounting', 'Balance Sheet']
  },
  {
    id: '11',
    title: 'Python Programming',
    course: 'BCA',
    semester: '2nd',
    subject: 'Python',
    subjectCode: 'BCA204',
    examType: 'Mid Semester',
    academicYear: '2023-2024',
    university: 'BBD ITM',
    downloads: 1400,
    rating: 4.9,
    uploadedBy: 'Riya Singh',
    createdAt: '2024-03-25T11:00:00Z',
    tags: ['Python', 'Oops', 'Data Types']
  },
  {
    id: '12',
    title: 'Web Technologies',
    course: 'B.Tech Computer Science',
    semester: '5th',
    subject: 'Web Technologies',
    subjectCode: 'KCS502',
    examType: 'Class Test',
    academicYear: '2023-2024',
    university: 'BBD NITM',
    downloads: 300,
    rating: 4.0,
    uploadedBy: 'Mohit Yadav',
    createdAt: '2023-10-15T15:20:00Z',
    tags: ['HTML', 'CSS', 'JavaScript']
  },
  {
    id: '13',
    title: 'Thermodynamics',
    course: 'B.Tech Mechanical Engineering',
    semester: '3rd',
    subject: 'Thermodynamics',
    subjectCode: 'KME301',
    examType: 'End Semester',
    academicYear: '2022-2023',
    university: 'AKTU',
    downloads: 820,
    rating: 4.5,
    uploadedBy: 'Ankit Tiwari',
    createdAt: '2022-12-05T10:10:00Z',
    tags: ['Heat', 'Laws of Thermodynamics']
  },
  {
    id: '14',
    title: 'Theory of Automata and Formal Languages',
    course: 'B.Tech Computer Science',
    semester: '4th',
    subject: 'TAFL',
    subjectCode: 'KCS402',
    examType: 'End Semester',
    academicYear: '2023-2024',
    university: 'BBD University',
    downloads: 1560,
    rating: 4.7,
    uploadedBy: 'Admin',
    createdAt: '2024-05-12T13:45:00Z',
    tags: ['Turing Machine', 'DFA', 'NFA']
  },
  {
    id: '15',
    title: 'Computer Organization and Architecture',
    course: 'B.Tech Information Technology',
    semester: '3rd',
    subject: 'COA',
    subjectCode: 'KIT301',
    examType: 'Mid Semester',
    academicYear: '2023-2024',
    university: 'BBD ITM',
    downloads: 650,
    rating: 4.2,
    uploadedBy: 'Sanjay Kumar',
    createdAt: '2023-11-20T16:00:00Z',
    tags: ['CPU', 'ALU', 'Pipelining']
  },
  {
    id: '16',
    title: 'Fluid Mechanics',
    course: 'B.Tech Mechanical Engineering',
    semester: '4th',
    subject: 'Fluid Mechanics',
    subjectCode: 'KME402',
    examType: 'End Semester',
    academicYear: '2023-2024',
    university: 'BBD NITM',
    downloads: 480,
    rating: 4.6,
    uploadedBy: 'Rohit Chauhan',
    createdAt: '2024-05-18T09:30:00Z',
    tags: ['Fluids', 'Bernoulli', 'Viscosity']
  },
  {
    id: '17',
    title: 'Structural Analysis',
    course: 'B.Tech Civil Engineering',
    semester: '5th',
    subject: 'Structural Analysis',
    subjectCode: 'KCE501',
    examType: 'End Semester',
    academicYear: '2022-2023',
    university: 'AKTU',
    downloads: 510,
    rating: 4.4,
    uploadedBy: 'Rajat Agarwal',
    createdAt: '2023-01-05T14:15:00Z',
    tags: ['Beams', 'Trusses', 'Frames']
  },
  {
    id: '18',
    title: 'Marketing Management',
    course: 'MBA',
    semester: '2nd',
    subject: 'Marketing Management',
    subjectCode: 'MBA201',
    examType: 'Mid Semester',
    academicYear: '2023-2024',
    university: 'Lucknow University',
    downloads: 730,
    rating: 4.5,
    uploadedBy: 'Admin',
    createdAt: '2024-04-10T11:00:00Z',
    tags: ['Marketing Strategy', 'Consumer Behavior']
  },
  {
    id: '19',
    title: 'Microprocessors',
    course: 'B.Tech Electronics & Communication',
    semester: '5th',
    subject: 'Microprocessors',
    subjectCode: 'KEC502',
    examType: 'End Semester',
    academicYear: '2023-2024',
    university: 'BBD University',
    downloads: 920,
    rating: 4.8,
    uploadedBy: 'Pooja Joshi',
    createdAt: '2024-01-02T10:30:00Z',
    tags: ['8085', 'Assembly Language', 'Interfacing']
  },
  {
    id: '20',
    title: 'Cyber Security',
    course: 'B.Tech Computer Science',
    semester: '6th',
    subject: 'Cyber Security',
    subjectCode: 'KCS603',
    examType: 'Class Test',
    academicYear: '2023-2024',
    university: 'BBD ITM',
    downloads: 1200,
    rating: 4.9,
    uploadedBy: 'Aditya Raj',
    createdAt: '2024-02-28T12:00:00Z',
    tags: ['Cryptography', 'Network Security', 'Hacking']
  }
]
